### ISSUE TITLE
setup-chromedriver action failed in v1.0.6

### ISSUE THREAD

**Issue by tsuzu** [nanasess/setup-chromedriver#41]
### Environment:
- OS: ubuntu-latest

### Workflow
```
on:
  push:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: nanasess/setup-chromedriver@v1.0.6
```

### Error log
https://github.com/tsuzu/test-setup-chromedriver/runs/5604411670?check_suite_focus=true
```
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module './oidc-utils'
Require stack:
- /home/runner/work/_actions/nanasess/setup-chromedriver/v1.0.6/node_modules/@actions/core/lib/core.js
- /home/runner/work/_actions/nanasess/setup-chromedriver/v1.0.6/lib/setup-chromedriver.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:66[7](https://github.com/go-generalize/api_gen/runs/5603867417?check_suite_focus=true#step:4:7):27)
    at Module.require (internal/modules/cjs/loader.js:[8](https://github.com/go-generalize/api_gen/runs/5603867417?check_suite_focus=true#step:4:8)87:1[9](https://github.com/go-generalize/api_gen/runs/5603867417?check_suite_focus=true#step:4:9))
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/nanasess/setup-chromedriver/v1.0.6/node_modules/@actions/core/lib/core.js:37:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:[10](https://github.com/go-generalize/api_gen/runs/5603867417?check_suite_focus=true#step:4:10)27:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:[14](https://github.com/go-generalize/api_gen/runs/5603867417?check_suite_focus=true#step:4:14))
    at Module.require (internal/modules/cjs/loader.js:887:[19](https://github.com/go-generalize/api_gen/runs/5603867417?check_suite_focus=true#step:4:19)) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/nanasess/setup-chromedriver/v1.0.6/node_modules/@actions/core/lib/core.js',
    '/home/runner/work/_actions/nanasess/setup-chromedriver/v1.0.6/lib/setup-chromedriver.js'
  ]
}
```

**Comment by tsuzu** [comment]
Duplicate of #40 
Sorry
